### ISSUE TITLE
Example transmission-proxy.yaml for common uses?

### ISSUE THREAD

**Issue by cannadayr** [vtavernier/transmission-proxy#1]
Hello! I went thru your project and it seems really cool and might work for my use-case.

I'd like to use the proxy to provide read-only access to a transmission remote control.

Have you used this for anything similar? Would you be willing to share an example transmission-proxy.yaml I can test and modify?

Thanks,

- Rowan

**Comment by vtavernier** [comment]
Hello Rowan, thanks for your interest in the project!

I haven't spent much time on documentation for now, but your use case is definitely doable with something along the lines of this:
```yaml
# transmission-proxy.yaml
acl:
  rules:
    - identities:
        - provider: basic
          name: admin
        - provider: oauth2
          oauth2: google
          name: admin@gmail.com
    - identities:
        - provider: basic
          name: readonly
        - provider: oauth2
          oauth2: google
          name: readonly@gmail.com
      allowed_methods:
        - torrent-get
        - session-get
        - session-stats
        - free-space
    - deny: true

providers:
  basic:
    enabled: true
    visible: false
    users:
      - username: admin
        password: "*bcrypt hash of the password*"
      - username: readonly
        password: "*bcrypt hash of the password*"
  oauth2:
    -
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      client_id: ...
      client_secret: ...
      email_path: $.email
      name: google
      token_url: https://www.googleapis.com/oauth2/v3/token
      userinfo_url: https://www.googleapis.com/oauth2/v3/userinfo
```

Here, we have 3 ACL rules:
- The first one matches an `admin` user, either through basic auth or through the configured Google OAuth2 provider. It allows all methods (the default).
- The second one matches a `readonly` user, also through basic auth or through Google OAuth2. Since we only allow read-only methods of the Transmission RPC API, this will result in a read-only profile.
- The last one is the default rule which denies access to unauthorized users.
